name: : CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: docker build -t dalavaro/skypro_mart:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: push
        run: docker push dalavaro/skypro_mart:$GIgsTHUB_REF_NAME-$GITHUB_RUN_ID